version: '3.8'
services:

  web:
    build: .
    command: bash -c "python manage.pyc collectstatic --noinput && python manage.pyc makemigrations && python manage.pyc migrate  && python manage.pyc runserver 0.0.0.0:8000"
    container_name: inventory
    links:
      - db
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=device

    volumes:
      - ./DB/init:/docker-entrypoint-initdb.d/:ro